export const JMS_USERNAME = "admin"
export const JMS_PASSWORD = "admin"
export const BROKER_URL = "ws://localhost:61616"
export const PUBLISH_QUEUE = "streaming-service-heartbeats"
export const SUBSCRIBER_QUEUE = "analyzed-images-stream"
export const TYPE = "nl.rug.eai.imagestream.commons.model.StreamConsumerHeartbeatEvent"